### PR TITLE
Fixes #19016 - change qpid to localhost

### PR DESCRIPTION
**Pull request by Klaas-**

### CODE REVIEW

**Comment by Klaas-** [comment]
Tests are broken for Puppet 3.5 (not by my change as far as I can tell)

**Comment by Klaas-** [comment]
I think a dependency or 2nd level dependency stopped supporting puppet3 :)

**Comment by ekohl** [comment]
@Klaas- that's very possible, I know voxpupli and puppetlabs are working on it. It's why I've been pushing on dropping Puppet 3 after the Foreman 1.15 branching (which is soon).

**Comment by Klaas-** [comment]
@ekohl how to we continue here? it's failing because it pulls https://github.com/puppetlabs/puppetlabs-xinetd master and that one dropped puppet3 support. Should I specify a tag for that repo that works or is it acceptable to fail on the old puppet version?

**Comment by ehelms** [comment]
Hrmm, we might be able to remove xinetd. This puppet module used to wrap foreman_proxy and thus required a lot of the fixtures it had. I'd bet a lot of those are not needed anymore.

**Comment by ekohl** [comment]
The default puppet-foreman_proxy sets up tftp as well. We can set parameters to turn that off as well with the benefit of faster tests.

**Comment by Klaas-** [comment]
@ekohl I fixed the new lint tests and the fixture for puppet3 :)
although I'm not sure why it enforces the ordering arrows to be on the other lines... :)

**Comment by ekohl** [comment]
It's the new style since puppet-lint 2.2.0. We just merged a bunch of the changes for theforeman and we should do the same for katello.

**Comment by stbenjam** [comment]
Ugh, I'd rather disable that lint check, it's hideous.

**Comment by ehelms** [comment]
I agree, its like the leading comma's in JavaScript which were just silly IMO.

**Pull request merged**
